name: Trigger xml2md

on:
  push:
    tags:
      - 'release-*'

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    name: Dispatch event

    steps:
    - name: Get version info
      id:   tag
      run:  echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Archive
      id: create-archive
      run: |
        zip -r Release $(find . -iname *.xml -o -iname *.png)
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.tag }}
        release_name: ${{ github.event.client_payload.tag }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./Release.zip
        asset_name: Release.zip
        asset_content_type: application/zip
    - uses: juztcode/repo-ditpatch-action@v1
      with:
        event-type: release_event
        token: ${{ secrets.REPO_TRIGGER_KEY }}
        repository: "${{ github.repository_owner }}/xml2md"
        client-payload: '{"tag": "${{ steps.tag.outputs.TAG }}" }'
